### ISSUE TITLE
Turn on spell check for en_US?

### ISSUE THREAD

**Issue by JBlackCat** [spikegrobstein/vim-config#4]
@spikegrobstein would it be helpful to turn on spell check by default?

If possible, perhaps we should do this for certain file types, such as `*.md` and ` *.txt`.

**Comment by spikegrobstein** [comment]
I thought about it, but my markdown files have so many "misspelled" words in them that it's just too much noise to see all that.

**Comment by JBlackCat** [comment]
ah, hadn't checked how accurate it actually was, only tested a small sample file.

**Comment by spikegrobstein** [comment]
it's mostly that most of the markdown I edit is documentation and things like function names, etc are not legit english words.

**Comment by JBlackCat** [comment]
Good point, I'll close unless I find a good work around. 😸
