### ISSUE TITLE
Migrate syntax plugins to vim-polyglot

### ISSUE THREAD

**Issue by JBlackCat** [spikegrobstein/vim-config#5]
@spikegrobstein any qualms with replacing the following with this single wrapper plugin, [vim-polyglot](https://github.com/sheerun/vim-polyglot)?

+ derekwyatt/vim-scala
+ elixir-lang/vim-elixir
+ elzr/vim-json
+ evanmiller/nginx-vim-syntax *replaced by https://github.com/othree/nginx-contrib-vim*
+ fatih/vim-go
+ honza/dockerfile.vim
+ nono/vim-handlebars **deprecated** *replaced by https://github.com/mustache/vim-mustache-handlebars*
+ pangloss/vim-javascript
+ plasticboy/vim-markdown
+ tpope/vim-haml
+ vim-ruby/vim-ruby

vim-polyglot would also add a bunch of additional syntax support without making the plugins file super messy.

If you rather not go the vim-polyglot route, is it ok to make a PR for  adding https://github.com/tikhomirov/vim-glsl instead?

**Comment by spikegrobstein** [comment]
vim-polyglot looks good.

do it, send me a PR!
