### ISSUE TITLE
Syntax: *.inc files should have HTML syntax highlighting

### ISSUE THREAD

**Issue by JBlackCat** [spikegrobstein/vim-config#7]
*.inc files should have HTML syntax highlighting

@spikegrobstein add this or leave as a custom derivative in my local branch.

**Comment by JBlackCat** [comment]
bump

**Comment by spikegrobstein** [comment]
hmmm... I would keep that in your own.

I generally would do `.html.inc` and have that be html highlighted, since sometimes I also have `.php.inc` files.

**Comment by JBlackCat** [comment]
Ah makes sense. Closing.
